# Generated by Django 2.0.7 on 2018-07-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('appetizer', 'Appetizer'), ('soup_or_salad', 'Soup or Salad'), ('main', 'Main Course'), ('dessert', 'Dessert')], db_index=True, max_length=32)),
            ],
        ),
    ]
