# Generated by Django 2.1.7 on 2019-03-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('Appetizer', 'Appetizer'), ('Soup or Salad', 'Soup or Salad'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert')], db_index=True, max_length=63)),
                ('image_url', models.CharField(blank=True, max_length=511, null=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('is_special', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
